name: Easy Old School Build

on:
  push: 
    branches:
      - dev
  workflow_dispatch:
    inputs:
      APP_ENV:
        description: 'APP_ENV (one of): development, staging, production'
        required: true
        default: 'staging'
      AUTO_SUBMIT:
        description: 'AUTO_SUBMIT (one of): true, false'
        required: true
        default: 'false'
      ANDROID:
        description: 'Run for ANDROID (one of): true, false'
        required: true
        default: 'true'
      VERSION:
        description: 'VERSION'
        required: true
        default: '0.0.0'
      IOS:
        description: 'Run for IOS (one of): true, false'
        required: true
        default: 'false'


  release:
    types: [published]

jobs:
  Build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      
  
      - name: 📦 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
  
      - name: ⚙️ Run Prebuild
        run: pnpm prebuild:staging
        shell: bash
  
      - name: 📱 Run Android Build
        run: |
          cd ./android 
          chmod +x ./gradlew
          ./gradlew assembleRelease
        shell: bash
      
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk